name: Draft PDF
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
    paths:
      - paper/**
      - .github/workflows/draft-pdf.yml
  pull_request:
    paths:
      - paper/**
      - .github/workflows/draft-pdf.yml

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: paper/paper.pdf

      # Only commit when NOT running from a pull request
      - name: Commit PDF to repository
        if: github.event_name != 'pull_request'
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Paper PDF Draft'
          add: 'paper/paper.pdf'